language: minimal

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake
            - libssl-dev
            - libglib2.0-dev

env:
    matrix:
        - PROJECT=embed-resources
        - PROJECT=popen-example
        - PROJECT=png-example
        - PROJECT=openssl-examples
        - PROJECT=walk-directory
        - PROJECT=mmap-file
        - PROJECT=find-in-files
        - PROJECT=dbus-example

script:
    - mkdir -p "$PROJECT/build"
    - cd "$PROJECT/build"
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
