language: minimal

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake

env:
    matrix:
        - PROJECT=embed-resources
        - PROJECT=popen-example

script:
    - mkdir -p "$PROJECT/build"
    - cd "$PROJECT/build"
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
