language: minimal

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake
            - libssl-dev

env:
    matrix:
        - PROJECT=embed-resources
        - PROJECT=popen-example
        - PROJECT=png-example
        - PROJECT=openssl-examples

script:
    - mkdir -p "$PROJECT/build"
    - cd "$PROJECT/build"
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
